# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Caller Workflow
on: [push, pull_request]


jobs: 

  call-workflow-ubuntu:
    strategy:
      matrix:
        os: ['ubuntu-latest']    
    uses: andife/onnx/.github/workflows/release_linux_x86_64.yml@20240710_start_reuseableworkflow    
    with:      
      node: "14"
      os: "linux"

  call-workflow-win:
    strategy:
      matrix:
        os: ['windows-latest']    
    uses: andife/onnx/.github/workflows/release_win.yml@20240710_start_reuseableworkflow   
    with:      
      node: "14"
      os: "win"

  call-workflow-mac:
    strategy:
      matrix:
        os: ['mac-latest']    
    uses: andife/onnx/.github/workflows/release_mac.yml@20240710_start_reuseableworkflow   
    with:      
      node: "14"
      os: "mac"

  