# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Caller Workflow
on: [push, pull_request]
jobs:
  build:
    uses: ./.github/workflows/release_linux_x86_64.yml
    with:      
      node: "14"
      os: "linux"
