# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Caller Workflow
on: [push, pull_request]
jobs:
  build:

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os}}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: RunLinux
        if: matrix.os == 'ubuntu-latest'
        uses: ./release_linux_x86_64.yml
        with:      
          node: "14"
          os: "linux"

      - name: RunLWindows
        if: matrix.os == 'windows-latest'
        uses: ./release_win.yml
        with:      
          node: "14"
          os: "win"
