# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Caller Workflow
on: 
  schedule:
    # Run weekly on Monday 00:00
    - cron:  '00 00 * * MON'
  push:
    branches: [main, rel-*,20240710_start_reuseableworkflow]
  pull_request:
    branches: [main, rel-*]


jobs: 

  call-workflow-ubuntu:
    strategy:
      matrix:
        os: ['ubuntu-latest']    
    uses: andife/onnx/.github/workflows/release_linux_x86_64.yml@20240710_start_reuseableworkflow    
    with:      
      node: "14"
      os: "linux"

  # call-workflow-win:
  #   strategy:
  #     matrix:
  #       os: ['windows-latest']    
  #   uses: andife/onnx/.github/workflows/release_win.yml@20240710_start_reuseableworkflow   
  #   with:      
  #     node: "14"
  #     os: "win"

  call-workflow-mac:
    strategy:
      matrix:
        os: ['mac-latest']    
    uses: andife/onnx/.github/workflows/release_mac.yml@20240710_start_reuseableworkflow   
    with:      
      node: "14"
      os: "mac"


  github-release:
    name: Prepare Files for Github Release
    runs-on: ubuntu-latest
    needs: [call-workflow-ubuntu, call-workflow-mac]
    if: always() && (needs.call-workflow-ubuntu.result == 'success') && ((needs.call-workflow-mac.result == 'success'))

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels* # TODO change back to python-wheels?
          path: dist
          merge-multiple: true


      - name: Sign the dists with Sigstore #/home/runner/work/onnx/onnx/dist/*.tar.gz
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-            
            /home/runner/work/onnx/onnx/dist/*.whl
  
      - name: Rename files # to match new file extension https://github.com/sigstore/sigstore-python/blob/main/CHANGELOG.md#changed
        run: |
          sudo apt install mmv 
          mmv "/home/runner/work/onnx/onnx/dist/*.sigstore" /home/runner/work/onnx/onnx/dist/#1.sigstore.json
      
      
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        with:
          name: sigstore-files
          path: |
              /home/runner/work/onnx/onnx/dist/*.sigstore.json
                


      - name: Upload artifact signatures to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/** 
          --repo '${{ github.repository }}'      